In [1]:
import pandas as pd
import numpy as np
train = pd.read_csv('Datasets/train.csv')
test = pd.read_csv('Datasets/test.csv')

In [2]:
train

,id,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
0,0,F,0.550,0.430,0.150,0.7715,0.3285,0.1465,0.2400,11
1,1,F,0.630,0.490,0.145,1.1300,0.4580,0.2765,0.3200,11
2,2,I,0.160,0.110,0.025,0.0210,0.0055,0.0030,0.0050,6
3,3,M,0.595,0.475,0.150,0.9145,0.3755,0.2055,0.2500,10
4,4,I,0.555,0.425,0.130,0.7820,0.3695,0.1600,0.1975,9
...,...,...,...,...,...,...,...,...,...,...
90610,90610,M,0.335,0.235,0.075,0.1585,0.0685,0.0370,0.0450,6
90611,90611,M,0.555,0.425,0.150,0.8790,0.3865,0.1815,0.2400,9
90612,90612,I,0.435,0.330,0.095,0.3215,0.1510,0.0785,0.0815,6
90613,90613,I,0.345,0.270,0.075,0.2000,0.0980,0.0490,0.0700,6
90614,90614,I,0.425,0.325,0.100,0.3455,0.1525,0.0785,0.1050,8

In [3]:
test

,id,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight
0,90615,M,0.645,0.475,0.155,1.2380,0.6185,0.3125,0.3005
1,90616,M,0.580,0.460,0.160,0.9830,0.4785,0.2195,0.2750
2,90617,M,0.560,0.420,0.140,0.8395,0.3525,0.1845,0.2405
3,90618,M,0.570,0.490,0.145,0.8740,0.3525,0.1865,0.2350
4,90619,I,0.415,0.325,0.110,0.3580,0.1575,0.0670,0.1050
...,...,...,...,...,...,...,...,...,...
60406,151021,I,0.345,0.260,0.085,0.1775,0.0735,0.0265,0.0500
60407,151022,F,0.525,0.410,0.145,0.8445,0.3885,0.1670,0.2050
60408,151023,I,0.590,0.440,0.155,1.1220,0.3930,0.2000,0.2650
60409,151024,F,0.660,0.525,0.190,1.4935,0.5885,0.3575,0.4350
60410,151025,F,0.430,0.340,0.120,0.4150,0.1525,0.0910,0.0905

In [4]:
df = pd.concat([train,test],sort = False)
df

,id,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
0,0,F,0.550,0.430,0.150,0.7715,0.3285,0.1465,0.2400,11.0
1,1,F,0.630,0.490,0.145,1.1300,0.4580,0.2765,0.3200,11.0
2,2,I,0.160,0.110,0.025,0.0210,0.0055,0.0030,0.0050,6.0
3,3,M,0.595,0.475,0.150,0.9145,0.3755,0.2055,0.2500,10.0
4,4,I,0.555,0.425,0.130,0.7820,0.3695,0.1600,0.1975,9.0
...,...,...,...,...,...,...,...,...,...,...
60406,151021,I,0.345,0.260,0.085,0.1775,0.0735,0.0265,0.0500,NaN
60407,151022,F,0.525,0.410,0.145,0.8445,0.3885,0.1670,0.2050,NaN
60408,151023,I,0.590,0.440,0.155,1.1220,0.3930,0.2000,0.2650,NaN
60409,151024,F,0.660,0.525,0.190,1.4935,0.5885,0.3575,0.4350,NaN
60410,151025,F,0.430,0.340,0.120,0.4150,0.1525,0.0910,0.0905,NaN

In [5]:
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
df.info()

<class 'pandas.DataFrame'>
Index: 151026 entries, 0 to 60410
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              151026 non-null  int64
 1   Sex             151026 non-null  str
 2   Length          151026 non-null  float64
 3   Diameter        151026 non-null  float64
 4   Height          151026 non-null  float64
 5   Whole weight    151026 non-null  float64
 6   Whole weight.1  151026 non-null  float64
 7   Whole weight.2  151026 non-null  float64
 8   Shell weight    151026 non-null  float64
 9   Rings           90615 non-null   float64
dtypes: float64(8), int64(1), str(1)
memory usage: 12.7 MB

In [7]:
df.isna().sum()

id                    0
Sex                   0
Length                0
Diameter              0
Height                0
Whole weight          0
Whole weight.1        0
Whole weight.2        0
Shell weight          0
Rings             60411
dtype: int64

In [8]:
df.drop(['Cabin','Name','Ticket'],axis=1,inplace= True)

KeyError: "['Cabin', 'Name', 'Ticket'] not found in axis"

In [ ]:
from sklearn.impute import SimpleImputer
print(f"Number of null values in Age Columns before imputation: {df.Age.isnull().sum()}")
si = SimpleImputer(strategy='mean')
df['Age']=si.fit_transform(df[['Age']])
print(f"Number fo Null values in Age columns after Imputation: '{df.Age.isnull().sum()}")

Number of null values in Age Columns before imputation: 0
Number fo Null values in Age columns after Imputation: '0

In [ ]:
df['Survived']=si.fit_transform(df[['Survived']])
si_freq = SimpleImputer(strategy='most_frequent')
df['Embarked']=si_freq.fit_transform(df[['Embarked']])
# .flatten()

ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
df["Fare"]= si.fit_transform(df[['Fare']])
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [ ]:
df.drop(['Name','Ticket'],axis=1,inplace= True)

**Z-Score & Outlier Detection** : -
Z-score helps to understand if a data value is greater or smaller than mean and how far away it is from the mean.More specifically, Z score tells how many standard deviations away a data point is from the mean

In [ ]:
threshold = 3
from scipy.stats import zscore
numerical_features = ['Fare','Age']
z_score = np.abs(zscore(df[numerical_features]))
print(z_score)

[[0.85138685 0.96184978]
 [1.86789136 1.0871246 ]
 [0.84171053 0.44960618]
 ...
 [0.85138685 1.15115505]
 [0.83479888 0.0474158 ]
 [0.04364635 0.0474158 ]]

In [ ]:
outliers = np.where(z_score > threshold)
print(outliers)

(array([], dtype=int64), array([], dtype=int64))

In [ ]:
from scipy.stats.mstats import winsorize
df['Age'] = winsorize(df['Age'],limits = [0.15,0.15])
df['Fare'] = winsorize(df['Fare'],limits = [0.15,0.15])

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
df['Sex'] = oe.fit_transform(df[['Sex']])

In [ ]:
df['Embarked'] = oe.fit_transform(df[['Embarked']])

In [ ]:
df['Survived'] = oe.fit_transform(df[['Survived']])

In [ ]:
 df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0.0,3,1.0,22.000000,1,0,7.7500,2.0
1,2,2.0,1,0.0,38.000000,1,0,56.9292,0.0
2,3,2.0,3,0.0,26.000000,0,0,7.9250,2.0
3,4,2.0,1,0.0,35.000000,1,0,53.1000,2.0
4,5,0.0,3,1.0,35.000000,0,0,8.0500,2.0
...,...,...,...,...,...,...,...,...,...
413,1305,1.0,3,1.0,29.881138,0,0,8.0500,2.0
414,1306,1.0,1,0.0,39.000000,0,0,56.9292,0.0
415,1307,1.0,3,1.0,38.500000,0,0,7.7500,2.0
416,1308,1.0,3,1.0,29.881138,0,0,8.0500,2.0
417,1309,1.0,3,1.0,29.881138,1,1,22.3583,0.0

In [ ]:
X= df.drop('Survived',axis =1)
y= df['Survived']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=0)

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
ab= AdaBoostClassifier(n_estimators=100,learning_rate=1,random_state=0)
ab.fit(X_train,y_train)

y_pred = ab.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_pred,y_test)
confusion_matrix(y_pred,y_test)

array([[ 76,   0,  10],
       [  0, 134,   0],
       [ 66,   0, 107]])